Fixes #158 & #113: Implement environment variables files and main refactor
MobilityData/mobility-database-interface pull request #159
Opened 2021-03-17 14:48 UTC by maximearmstrong

**Summary:**

Fixes #158: Implement environment variables process for staging/production
Fixes #113: Refactor main.py

This PR main goal is to implement environment variables for staging and production deployment.
Implementing these demanded many modifications to `main.py`, leaving only few modification to do for #113. Because of this, #113 is also fixed by this PR (removing unused arguments and functions).

Implement

- `.env.template` is added to the repo. Every of the variables in this file must be assigned a value in an `.env.FILE`, that is to be passed as argument to `main.py`.

Changes

- `main.py` was modified so that the imports related to the project are made after loading the environment. A new argument `--path_to_env_var` was added. Default is set to `./.env.staging`, but any `.env.FILE` containing all the environment variables may be passed as argument.

**Expected behavior:** 

Same as before, but an environment variables file must be present in the repo (`.env.staging`), any file containing the environment variables (`.env.FILE`) must be passed as argument otherwise.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `pytest` to make sure you didn't break anything
- [x] Format the title like "<short description of fix and changes>" (for example - "Check for null value before using field")
- [x] Linked all relevant issues
- [ ] ~Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2021-03-17 17:44 UTC, annaelleduff requested changes

2021-03-17 17:44 UTC, annaelleduff commented on main.py
> +        "--path_to_tmp_data",
you can use `-` here as it's easier to type, and args parse will take care of making it an `_` for the attribute name

2021-03-17 17:44 UTC, annaelleduff commented on utilities/constants.py
> +GTFS_CATALOG_OF_SOURCES_CODE = os.environ.get("GTFS_CATALOG_OF_SOURCES_CODE")
A thought: 
staging env vars and prod env var will be versionned and committed so having them as env var there seems risky. We should look into using secrets on k8s or something like that.

And, I would maybe separate env var constants and string constants as the file is getting pretty big. What do you think?

2021-03-17 17:59 UTC, maximearmstrong commented on main.py
> +        "--path_to_tmp_data",
Didn't know that, thanks!

2021-03-22 18:55 UTC, maximearmstrong commented on utilities/constants.py
> +GTFS_CATALOG_OF_SOURCES_CODE = os.environ.get("GTFS_CATALOG_OF_SOURCES_CODE")
I separated `constants.py` in 2, but let's discuss the best option for the credentials before committing the env files.

2021-03-29 16:56 UTC, annaelleduff commented on main.py
> +    create_dataset_env_vars = {
Could you explain what this does?  this dictionary doesn't seem to be used.

2021-03-29 17:15 UTC, maximearmstrong commented on main.py
> +    create_dataset_env_vars = {
Right. I forgot to delete it. It was previously passed to the `create_dataset_entity_for_gtfs_metadata` use case.

2021-03-29 19:55 UTC, annaelleduff approved these changes

2021-03-29 20:06 UTC, merged