Fixes #173: Implement Country code use case
MobilityData/mobility-database-interface pull request #179
Opened 2021-04-15 22:10 UTC by maximearmstrong

**Summary:**

Fixes #173: Implement Country code use case

This PR implement the Country code use case by leveraging the [reverse_geocoder](https://pypi.org/project/reverse_geocoder/) python library

Implement

- `process_country_codes_for_gtfs_metadata.py` and tests

This PR contains changes to

- `main.py` and `create_dataset_entity_for_gtfs_metadata.py` were modified to reflect changes
- `.env.staging` and `.env.production` were modified to add the country code property

**Expected behavior:** 

Country codes are processed during the metadata extraction.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `pytest` to make sure you didn't break anything
- [x] Format the title like "<short description of fix and changes>" (for example - "Check for null value before using field")
- [x] Linked all relevant issues
- [ ] ~Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2021-04-21 17:13 UTC, annaelleduff commented on requirements.txt
> +scipy==1.6.2
why is scipy added? I might have missed an import but I don't see it

2021-04-21 20:55 UTC, lionel-nj commented on .env.production
> +COUNTRY_CODE_PROP = "P8"
I might be missing something here, but should this be `""`?

2021-04-21 20:57 UTC, maximearmstrong commented on .env.production
> +COUNTRY_CODE_PROP = "P8"
This is normal, all the other ones are fixed in #170

2021-04-21 21:13 UTC, lionel-nj requested changes
Overall, LGTM! Just one additional unit test could be implemented to make sure this new use case works properly. 

Just making sure, if any row of the provided GTFS dataset has no lat or lon (i.e. the validation report contains a `MissingRequiredFieldNotice`  notice for latitude and/or longitude), this use case will not be called right?

2021-04-21 21:13 UTC, lionel-nj commented on usecase/test/test_process_country_codes_for_gtfs_metadata.py
> +    def test_process_country_codes_with_lat_lon(self, mock_rg):
One more unit test could consist in using out of range values for latitudes and longitudes: (lat=850, lon=-4000). The resulting set of country codes should be empty.

2021-04-21 22:53 UTC, maximearmstrong commented on usecase/test/test_process_country_codes_for_gtfs_metadata.py
> +    def test_process_country_codes_with_lat_lon(self, mock_rg):
Ah! I thought `reverse_geocoder` would crash on this, but indeed it just returns nothing so I added the test. We want the use cases to fail on invalid value such as (lat=850, lon=-4000). This will be captured by validating the use cases with the Validator output in #172. For example, (lat=850, lon=-4000) will generated a `number_out_of_range` notice for file `stops.txt`, so the use case won't be kept after verification.

2021-04-22 14:06 UTC, lionel-nj approved these changes
LGTM 👍🏾

2021-04-22 17:50 UTC, merged