Fixes #181: Validate necessary files and fields for GTFS metadata extraction
MobilityData/mobility-database-interface pull request #183
Opened 2021-04-19 22:50 UTC by maximearmstrong

**Summary:**

This PR makes sure the necessary files/fields are present in the GTFS dataset representation (via GTFS Kit) before executing a use case. Even though a dataset could be valid, its representation as a GTFS Kit object has to be validated so the code doesn't crash. Also, this allows to extract the metadata without validating the dataset with the [Validator](https://github.com/MobilityData/gtfs-validator) prior to metadata extraction. However, validating the dataset with the Validator would be optimal.

This PR contains changes to

- GTFS metadata extraction use cases and their tests.

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `pytest` to make sure you didn't break anything
- [x] Format the title like "<short description of fix and changes>" (for example - "Check for null value before using field")
- [x] Linked all relevant issues
- [ ] ~Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2021-04-21 17:37 UTC, annaelleduff commented on usecase/process_timestamp_for_gtfs_metadata.py
> +        ).issubset(dataset.calendar.columns)
for redability, 

```
CALENDAR_NECESSARY_COLUMNS.union(
            {timestamp_map[CALENDAR_DATE_KEY]}
        ).issubset(dataset.calendar.columns)
```

should be in a var

2021-04-21 19:17 UTC, maximearmstrong commented on usecase/process_timestamp_for_gtfs_metadata.py
> +        ).issubset(dataset.calendar.columns)
I put every `issubset()` comparison in a var so it's clearer. Done in `process_timestamp_for_gtfs_metadata.py`, `process_service_date_for_gtfs_metadata.py` and `process_geographical_boundaries_for_gtfs_metadata.py`.

2021-04-21 21:56 UTC, lionel-nj commented on utilities/temporal_utils.py
> +    MONDAY,
🤩

2021-04-21 21:57 UTC, lionel-nj commented on utilities/temporal_utils.py
> +    MONDAY,
🤩

2021-04-21 21:57 UTC, lionel-nj commented on utilities/constants.py
> +SPARQL_A = "a"
🤩

2021-04-21 22:40 UTC, lionel-nj requested changes
Thanks @maximearmstrong, here is a first set of comments. I'll be reviewing the test shortly.

2021-04-21 22:40 UTC, lionel-nj commented on utilities/validators.py
> +def is_valid_instance(prop_instance, prop_class):
Unit tests for these new methods should be implemented.

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_agencies_count_for_gtfs_metadata.py
> +        agencies_count = 0
Just wondering if It would be better to define `agency_count = 0` first then modify its value if `dataset.agency is not None and AGENCY_NAME in dataset.agency.columns`? 

But it would not change a lot of things to the logic here.

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_geopraphical_boundaries_for_gtfs_metadata.py
> +    else:
Same here for `geo_boundaries`

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_agencies_count_for_gtfs_metadata.py
> +    if dataset.agency is not None and AGENCY_NAME in dataset.agency.columns:
To improve code clarity, should this statement be a auxiliary method such as `isAgencyPresent`?

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_main_language_code_for_gtfs_metadata.py
> +        and not dataset.agency.empty
Same here, should we use `isAgencyEmpty`?

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_routes_count_by_type_for_gtfs_metadata.py
> +    if dataset.routes is not None and ROUTE_TYPE in dataset.routes.columns:
Same here, should we use `areRoutePresent`?

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_service_date_for_gtfs_metadata.py
> +CALENDAR_DATES_NECESSARY_COLUMNS = {
To stick to the GTFS specification, I would have name this variable `CALENDAR_DATES_REQUIRED_COLUMNS`. GBFS seems to use the same language also https://github.com/NABSA/gbfs/blob/master/gbfs.md.

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_stops_count_by_type_for_gtfs_metadata.py
> +    if dataset.stops is not None and LOCATION_TYPE in dataset.stops.columns:
Same here with `areStopPresent`?

2021-04-21 22:40 UTC, lionel-nj commented on usecase/process_timezones_for_gtfs_metadata.py
> +    if (
Same here with `isAgencyPresent`?

2021-04-21 22:40 UTC, lionel-nj commented on usecase/test/test_process_end_service_date_for_gtfs_metadata.py
> +
NIT - blank line

2021-04-21 22:58 UTC, maximearmstrong commented on usecase/process_service_date_for_gtfs_metadata.py
> +CALENDAR_DATES_NECESSARY_COLUMNS = {
I thought of it too. I changed it before you reviewed the PR, I will push it now.

2021-04-21 23:03 UTC, maximearmstrong commented on usecase/process_agencies_count_for_gtfs_metadata.py
> +        agencies_count = 0
This was my first idea, but this way we assigned the var only once. Also, the else statement makes it clear that the falsy assignment is because the files/fields are not present.

2021-04-21 23:05 UTC, maximearmstrong commented on usecase/process_agencies_count_for_gtfs_metadata.py
> +    if dataset.agency is not None and AGENCY_NAME in dataset.agency.columns:
I will assign it to a var (same for all the other ones below).

2021-04-21 23:35 UTC, maximearmstrong commented on usecase/test/test_process_end_service_date_for_gtfs_metadata.py
> +
`mock_dates_by_type` is patched and passed as parameter, this is just to easily locate it and help readability

2021-04-22 07:22 UTC, annaelleduff commented on utilities/validators.py
> +def is_valid_instance(prop_instance, prop_class):
😬 I think it's overkill. you'd end up testing python.
I'd suggest testing is_valid_instance only.
During my review I debated with myself about the usefulness of this set of functions. Decided that they were overkill but convenient.

@lionel-nj if you're not comfortable with not testing them all, then I'd suggest only keeping is_valid_instance (as it's the only one actually doing more than a call to a built-in python func) and passing the extra argument prop_class wherever is_valid_str/int/etc was called.

also if you want to list the falsy values, None and false are missing 😅

2021-04-22 13:12 UTC, lionel-nj commented on utilities/validators.py
> +def is_valid_instance(prop_instance, prop_class):
> 😬 I think it's overkill. you'd end up testing python.
> I'd suggest testing is_valid_instance only.

Makes sense to me 👍🏾

> @lionel-nj if you're not comfortable with not testing them all, then I'd suggest only keeping is_valid_instance (as it's the only one actually doing more than a call to a built-in python func) and passing the extra argument prop_class wherever is_valid_str/int/etc was called.

Looks like @maximearmstrong  already implemented tests for `is_valid_instance`. Sorry for the double work  😅

> also if you want to list the falsy values, None and false are missing 😅


Not sure to understand what you mean here

2021-04-22 13:25 UTC, annaelleduff commented on utilities/validators.py
> +def is_valid_instance(prop_instance, prop_class):
> also if you want to list the falsy values, None and false are missing
was meant for Max, sorry for the confusion. In the comment, there are examples of "falsy values", but either a "..." is missing or [the rest of the python "falsy" values are missing](https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/#-falsy-values)

2021-04-22 13:58 UTC, lionel-nj submitted a review, later dismissed
Thanks @maximearmstrong

2021-04-22 15:04 UTC, annaelleduff commented on usecase/process_routes_count_by_type_for_gtfs_metadata.py
> +    if dataset.routes is not None and ROUTE_TYPE in dataset.routes.columns:
May I suggests `route_not_none` to not obscure the fact that we're checking against None? 😬

2021-04-22 18:24 UTC, maximearmstrong commented on utilities/validators.py
> +def is_valid_instance(prop_instance, prop_class):
> also if you want to list the falsy values, None and false are missing 😅

Right. I used the falsy 

> During my review I debated with myself about the usefulness of this set of functions. Decided that they were overkill but convenient.

I was also unsure of these functions. I agree they are overkill, it was just to improve readability. 

> 😬 I think it's overkill. you'd end up testing python.
> I'd suggest testing is_valid_instance only.

I agree 😅

I will think to a better way to way to do all of this. This is not efficient nor elegant

2021-04-22 21:55 UTC, maximearmstrong commented on utilities/validators.py
> +def is_valid_instance(prop_instance, prop_class):
@annaelleduff @lionel-nj Ok so I modified this. From now, a use case is responsible to create the correct metadata attribute object. The different attributes in a `GtfsMetadata` object are initialize with None. A use case replaces a metadata attribute value if and only if the value is not empty (for str, list and dict) or greater than 0 (for int). 

The verification in `create_dataset_entity_for_gtfs_metadata.py` is now made only with the `isinstance()` function. We assume that if a metadata attribute is of the correct type, then it is valid because the use case did assigned it in the `GtfsMetadata` object. If it is not the case, and some incorrect values are stored (empty for example), WikibaseIntegrator will fail. In such case, a use case would be the problem and we want to catch it.

2021-04-23 16:20 UTC, lionel-nj commented on usecase/process_routes_count_by_type_for_gtfs_metadata.py
> +    if dataset.routes is not None and ROUTE_TYPE in dataset.routes.columns:
I was actually suggsting to replace `dataset.routes is not None and ROUTE_TYPE in dataset.routes.columns` by `areRoutePresent`. 

Using `route_not_none` would be used if we were trying to clarify `dataset.routes is not None`.

2021-04-27 08:40 UTC, annaelleduff commented on usecase/process_routes_count_by_type_for_gtfs_metadata.py
> +    if dataset.routes is not None and ROUTE_TYPE in dataset.routes.columns:
my point was: `dataset.routes is not None` becomes `routes_not_none` and the rest stays as is.
`areRoutePresent` obscures several things: the fact that we're checking against None, and that we are checking that route_type is in dataset.routes.column.
Maybe I'm being a bit too intense.
maybe the word present is not quite the word for it? 
Whichever makes the most sense to the team😅

2021-04-27 09:14 UTC, annaelleduff requested changes
most of my comments are just notes, you don't need to change the vars name if you think it's ok like this.
The one thing I would pay attention to is the isinstance(..., str) check without checking that the var is not an empty string. That's a check that was there before and that disappeared,

2021-04-27 09:14 UTC, annaelleduff commented on usecase/process_country_codes_for_gtfs_metadata.py
> +    if are_stops_present:
for readability I would rename this var stops_are_present

2021-04-27 09:14 UTC, annaelleduff commented on usecase/process_main_language_code_for_gtfs_metadata.py
> +    if is_agency_present:
same suggestion: agency_is_present ?

2021-04-27 09:14 UTC, annaelleduff commented on usecase/process_routes_count_by_type_for_gtfs_metadata.py
> +        # Count routes by route type
should the content of this if be in its own function that returns routes_count_by_type ?

2021-04-27 09:14 UTC, annaelleduff commented on usecase/process_service_date_for_gtfs_metadata.py
> +            dataset.feed_info is not None
`dataset.feed_info is not None` is being checked twice

2021-04-27 17:00 UTC, maximearmstrong commented on usecase/create_dataset_entity_for_gtfs_metadata.py
> +    if isinstance(metadata.main_language_code, str):
Ok so I kept my previous modifications, but I did add back the instances validators, so we are doing "double check"

2021-04-27 17:39 UTC, maximearmstrong commented on usecase/process_routes_count_by_type_for_gtfs_metadata.py
> +        # Count routes by route type
Do you mean line 43 to 99? I don't have strong feeling on this. It looks like we would move a big part of the use case to another function

2021-05-07 07:32 UTC, annaelleduff approved these changes

2021-05-07 07:32 UTC, merged