Fix #272: Source stable URLs ends up in a GTFS dataset stable URLs
MobilityData/mobility-database-interface pull request #273
Opened 2021-08-05 20:35 UTC by maximearmstrong

**Summary:**

Fix #272: Source stable URLs ends up in a GTFS dataset stable URLs

This PR makes sure that a download URL that isn't stable won't end up in the database. This was previously checked in `gtfs_metadata.py` during the `init()` of the object. Previously, create_dataset_entity_for_gtfs_metadata.py was extracting the archives_url and download_url from `gtfs_metadata.py`, but then this was changed so the URLs were taken from the `dataset_infos` object, allowing to create an entity on the database with minimal information when a problem occurred when processing a dataset.

Implement

This PR contains changes to

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `pytest` to make sure you didn't break anything
- [ ] Format the title like "<short description of fix and changes>" (for example - "Check for null value before using field")
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2021-08-11 18:16 UTC, lionel-nj commented on usecase/test/test_create_dataset_entity_for_gtfs_dataset.py
> +        test_archives_url = "https://storage.googleapis.com/storage/v1/b/somebucket/o/somedataset.zip?alt=media"
Also should it be a class constant since the value is reused on line 40 of this file?

2021-08-11 18:20 UTC, lionel-nj requested changes
Thanks for working on that @maximearmstrong. A few comments in-line: mostly suggestions to improve the readibility of tests.

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_download_url = "http://transitfeeds.com/p/societe-de-transport-de-montreal/39/20200811/download"
test_download_url -> stable_transit_feeds_url

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_download_url = "http://transitfeeds.com/p/societe-de-transport-de-montreal/39/latest/download"
test_download_url -> unstable_transit_feeds_url

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_download_url = "http://openmobilitydata.org/p/societe-de-transport-de-montreal/39/20200811/download"
test_download_url -> stable_omd_url

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_download_url = "http://openmobilitydata.org/p/societe-de-transport-de-montreal/39/latest/download"
test_download_url -> unstable_omd_url

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_download_url = "http://someotherurl"
invalid_url

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_download_url = ""
invalid_url_empty_string

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_archives_url = "https://storage.googleapis.com/storage/v1/b/presidigo-gtfs-q86239_archives_2021-08-05/o/1665ba7dc1bc982422c4f8c12bfa2e65cfce3905.zip?alt=media"
test_archives_url -> stable_archive_url

2021-08-11 18:20 UTC, lionel-nj commented on utilities/test/test_validators.py
> +        test_archives_url = ""
test_archives_url -> invalid_url_empty_string

2021-08-11 20:53 UTC, maximearmstrong commented on utilities/test/test_validators.py
> +        test_download_url = "http://transitfeeds.com/p/societe-de-transport-de-montreal/39/20200811/download"
test_stable_transit_feeds_url

2021-08-11 20:53 UTC, maximearmstrong commented on utilities/test/test_validators.py
> +        test_download_url = "http://transitfeeds.com/p/societe-de-transport-de-montreal/39/latest/download"
test_invalid_transit_feeds_url

2021-08-11 20:53 UTC, maximearmstrong commented on utilities/test/test_validators.py
> +        test_download_url = "http://openmobilitydata.org/p/societe-de-transport-de-montreal/39/20200811/download"
test_stable_omd_url

2021-08-12 21:13 UTC, lionel-nj requested changes
Thanks @maximearmstrong - 1 small change to before merging this PR

2021-08-12 21:13 UTC, lionel-nj commented on .pre-commit-config.yaml
> +      language_version: python3.9
This does not seem related to this PR, do you mind upgrading in a separate PR please? :)

2021-08-12 21:13 UTC, lionel-nj commented on usecase/test/test_create_dataset_entity_for_gtfs_dataset.py
> +        type(mock_dataset_infos).zip_path = TEST_ZIP_PATH
👍🏾

2021-08-16 17:56 UTC, maximearmstrong commented on .pre-commit-config.yaml
> +      language_version: python3.9
I can't commit without this :)

2021-08-18 20:11 UTC, maximearmstrong commented on .pre-commit-config.yaml
> +      language_version: python3.9
Done in #285

2021-08-19 14:15 UTC, lionel-nj approved these changes
lgtm, thanks :)

2021-08-19 14:16 UTC, merged